[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"  # If you're using Netlify Functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"